### ISSUE TITLE
Stereo Result

### ISSUE THREAD

**Issue by ZzhYgwh** [v4rl-ucy/HyperSLAM#15]
Thanks for the author and this open source work！
But now I am using the EuRoC dataset to reproduce the Stereo experiment, and the results of the evo evaluation make me a little confused, even though I used `-as` to align and correct the scale. Some reference pictures are as follows:
MH05
![stereo](https://github.com/user-attachments/assets/c75de0ad-9edd-4ee5-9e94-5636b2172ae0)
and V202.
![stereo2](https://github.com/user-attachments/assets/4973664d-c673-4271-8191-a98ae3d37b70)
I run this code as:
`./bin/HyperSLAM resources/datasets/euroc/setups/stereo/settings.yaml output/euroc/`
and modify the output file as TUM format
This seems to be completely unrelated to the truth trajectory. Is there anyone who can answer this question? Thank you very much!

**Comment by McEmzi** [comment]
@ZzhYgwh Thank you for your question. I am aware that some people raised questions/issues (see #11) related to the stereo-inertial operation, which was left to be added in a later patch. However, the stereo-only version seemed to be working for others. You mentioned some conversions to TUM format... Might it be possible that some columns of the position and/or quaternions have a different order than expected?
